CREATE DATABASE NTDL_DB;

USE NTDL_DB;

CREATE TABLE Usuarios (
    Usid INT(8) AUTO_INCREMENT PRIMARY KEY,
    Usname VARCHAR(30) NOT NULL,
    Correo VARCHAR(30) NOT NULL,
    pin VARCHAR(30) NOT NULL
);

CREATE TABLE Tareas (
    Taid INT(8) AUTO_INCREMENT PRIMARY KEY,
    Taname VARCHAR(30) NOT NULL,
    realizado BOOLEAN NOT NULL DEFAULT FALSE,
    Idus INT(8) NOT NULL
);